### PR TITLE
segregated different apps like login, employee, employer and segregate…

### PR DESCRIPTION
**Pull request by rjs08**
…ed templates

### CODE REVIEW

**Comment by thejasSD** [comment]
add me as reviewer not assignees

**Comment by thejasSD** [comment]
why files changed are 86
only commit and push files that you have changed

**Comment by rjs08** [comment]
I moved files from one app to three different apps that's why its showing changed 86 files

**Comment by rjs08** [comment]
also moved templates in three folders for employee, employer and login I think that also counted in that.

**Comment by thejasSD** [comment]
check properly

**Comment by thejasSD** [comment]
did you change 86 files? u should only commit the files you have changed

**Comment by rjs08** [comment]
yes have changed 86 files that's only committed

**Review by thejasSD — DISMISSED** [review]
i will show you later

**Pull request closed without merging**
